/**
 * Portal magic-link verify — GET Route Handler.
 *
 * WHY A ROUTE HANDLER (not a Server Component):
 * Next.js App Router Server Components CANNOT set cookies — any attempt to
 * call `cookieStore.set()` inside a Server Component is silently swallowed by
 * the try/catch in `createClient`. That means `verifyOtp` would consume the
 * OTP token on Supabase's side but NEVER write the session cookies to the
 * browser, so every subsequent request would be unauthenticated.
 *
 * Route Handlers (route.ts) DO have full cookie write access. We collect the
 * cookies Supabase wants to set and copy them onto the final redirect response
 * so the browser receives a valid session.
 *
 * The link in the email is:
 *   /portal/verify?token_hash=<hash>&type=magiclink&next=/portal
 * (generated by `generatePortalMagicLink` in `@/lib/portal/portal-activation`)
 */

import { createServerClient } from "@supabase/ssr";
import { type NextRequest, NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";
import type { Database } from "@/types/database";
import type { EmailOtpType } from "@supabase/supabase-js";

function sanitizeNext(value: string | null): string {
  if (!value) return "/portal";
  if (!value.startsWith("/")) return "/portal";
  if (value.startsWith("//")) return "/portal";
  if (!value.startsWith("/portal")) return "/portal";
  return value;
}

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;
  const tokenHash = searchParams.get("token_hash");
  const type = searchParams.get("type");
  const next = sanitizeNext(searchParams.get("next"));

  const errorUrl = new URL("/portal/login?error=invalid_link", request.url);

  if (!tokenHash || !type) {
    return NextResponse.redirect(errorUrl);
  }

  // Collect all cookies Supabase wants to write (session tokens) so we can
  // attach them to the redirect response.  A Map ensures we keep only the
  // latest value for each cookie name (e.g. after a sign-out self-heal).
  type CookieEntry = { value: string; options: Record<string, unknown> };
  const cookieMap = new Map<string, CookieEntry>();

  const supabase = createServerClient<Database>(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet) {
          cookiesToSet.forEach(({ name, value, options }) =>
            cookieMap.set(name, { value, options: options ?? {} }),
          );
        },
      },
    },
  );

  const { error: verifyError } = await supabase.auth.verifyOtp({
    type: type as EmailOtpType,
    token_hash: tokenHash,
  });

  if (verifyError) {
    console.error("[portal/verify] verifyOtp error:", verifyError);
    return NextResponse.redirect(errorUrl);
  }

  // Verify portal linkage and self-heal if needed.
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (user) {
    const admin = createAdminClient();
    const { data: client } = await admin
      .from("clients")
      .select("id, portal_user_id, has_portal_access")
      .eq("portal_user_id", user.id)
      .eq("has_portal_access", true)
      .maybeSingle();

    if (!client) {
      // Try to link by email in case portal_user_id wasn't set yet.
      if (user.email) {
        const { data: byEmail } = await admin
          .from("clients")
          .select("id")
          .eq("email", user.email.toLowerCase())
          .eq("has_portal_access", true)
          .maybeSingle();

        if (byEmail) {
          await admin
            .from("clients")
            .update({ portal_user_id: user.id })
            .eq("id", byEmail.id);
        } else {
          // No portal access — sign out and redirect.
          await supabase.auth.signOut();
          const noAccessUrl = new URL(
            "/portal/login?error=no_access",
            request.url,
          );
          const noAccessResponse = NextResponse.redirect(noAccessUrl);
          cookieMap.forEach(({ value, options }, name) =>
            noAccessResponse.cookies.set(
              name,
              value,
              options as Parameters<typeof noAccessResponse.cookies.set>[2],
            ),
          );
          return noAccessResponse;
        }
      }
    }
  }

  // Build the redirect response and attach all session cookies so the browser
  // receives a fully authenticated session.
  const redirectResponse = NextResponse.redirect(new URL(next, request.url));
  cookieMap.forEach(({ value, options }, name) =>
    redirectResponse.cookies.set(
      name,
      value,
      options as Parameters<typeof redirectResponse.cookies.set>[2],
    ),
  );
  return redirectResponse;
}
