/**
 * PHASE AWD-03: AI Website Designer Core Engine
 * Core Type Definitions
 *
 * These types define the complete structure for AI website generation,
 * from input parameters to fully generated multi-page websites.
 */

import type { BusinessDataContext } from "./data-context/types";

// =============================================================================
// INPUT TYPES
// =============================================================================

/**
 * Style preferences for website generation
 */
export type WebsiteStyle =
  | "minimal"
  | "bold"
  | "elegant"
  | "playful"
  | "corporate"
  | "creative";

/**
 * Color preferences for design system
 */
export type ColorPreference =
  | "brand"
  | "warm"
  | "cool"
  | "monochrome"
  | "vibrant";

/**
 * Layout density options
 */
export type LayoutDensity = "spacious" | "balanced" | "compact";

/**
 * Animation intensity levels
 */
export type AnimationLevel = "none" | "subtle" | "moderate" | "dynamic";

/**
 * User preferences for website generation
 */
export interface WebsiteDesignerPreferences {
  style?: WebsiteStyle;
  colorPreference?: ColorPreference;
  layoutDensity?: LayoutDensity;
  animationLevel?: AnimationLevel;
}

/**
 * Constraints for website generation
 */
export interface WebsiteDesignerConstraints {
  maxPages?: number;
  requiredPages?: string[];
  excludeComponents?: string[];
  mustIncludeComponents?: string[];
}

/**
 * Main input for website designer
 */
export interface WebsiteDesignerInput {
  siteId: string;
  prompt: string;
  preferences?: WebsiteDesignerPreferences;
  constraints?: WebsiteDesignerConstraints;
}

// =============================================================================
// SITE INTENT & TONE
// =============================================================================

/**
 * Website intent/purpose types
 */
export type SiteIntent =
  | "portfolio"
  | "ecommerce"
  | "landing"
  | "corporate"
  | "blog"
  | "service"
  | "restaurant"
  | "real-estate"
  | "agency"
  | "saas"
  | "healthcare"
  | "construction"
  | "education"
  | "nonprofit"
  | "general";

/**
 * Brand tone options
 */
export type BrandTone =
  | "professional"
  | "playful"
  | "minimal"
  | "bold"
  | "elegant"
  | "friendly"
  | "authoritative"
  | "innovative";

// =============================================================================
// ARCHITECTURE TYPES
// =============================================================================

/**
 * Design tokens generated by AI
 */
export interface DesignTokens {
  primaryColor: string;
  secondaryColor?: string;
  accentColor?: string;
  backgroundColor?: string;
  textColor?: string;
  fontHeading: string;
  fontBody: string;
  borderRadius: "none" | "sm" | "md" | "lg" | "xl" | "full";
  shadowStyle: "none" | "subtle" | "soft" | "dramatic";
  spacingScale: "compact" | "balanced" | "spacious";
}

/**
 * Section plan for a page
 */
export interface SectionPlan {
  intent: string;
  suggestedComponent: string;
  alternativeComponents: string[];
  contentNeeds: string[];
  designNotes: string;
}

/**
 * Page plan within site architecture
 */
export interface PagePlan {
  name: string;
  slug: string;
  purpose: string;
  sections: SectionPlan[];
  priority: number;
}

/**
 * Navbar configuration plan
 */
export interface NavbarPlan {
  style: "sticky" | "fixed" | "static";
  variant: "minimal" | "modern" | "classic" | "transparent";
  ctaButton: boolean;
  ctaText?: string;
  ctaLink?: string;
}

/**
 * Footer configuration plan
 */
export interface FooterPlan {
  style: "minimal" | "simple" | "comprehensive" | "centered";
  columns: 1 | 2 | 3 | 4;
  newsletter: boolean;
  socialLinks: boolean;
  copyright: boolean;
}

/**
 * Complete site architecture generated by AI
 */
export interface SiteArchitecture {
  intent: SiteIntent;
  tone: BrandTone;
  pages: PagePlan[];
  sharedElements: {
    navbar: NavbarPlan;
    footer: FooterPlan;
  };
  designTokens: DesignTokens;
}

// =============================================================================
// GENERATED OUTPUT TYPES
// =============================================================================

/**
 * Individual generated component
 */
export interface GeneratedComponent {
  id: string;
  type: string;
  props: Record<string, unknown>;
  aiNotes?: string;
}

/**
 * SEO settings for a page
 */
export interface PageSEO {
  title: string;
  description: string;
  keywords?: string[];
  ogImage?: string;
  noIndex?: boolean;
}

/**
 * Generated page with all components
 */
export interface GeneratedPage {
  id: string;
  name: string;
  slug: string;
  title: string;
  description: string;
  isHomepage: boolean;
  components: GeneratedComponent[];
  seo: PageSEO;
  order: number;
}

/**
 * Navigation item
 */
export interface NavigationItem {
  label: string;
  href: string;
  order?: number;
  children?: NavigationItem[];
}

/**
 * Navigation structure
 */
export interface NavigationStructure {
  main: NavigationItem[];
  footer: NavigationItem[];
}

/**
 * Site-wide settings
 */
export interface SiteSettings {
  theme: "light" | "dark" | "system";
  language: string;
  timezone?: string;
  favicon?: string;
  socialImage?: string;
}

/**
 * Site-wide SEO settings
 */
export interface SEOSettings {
  title: string;
  description: string;
  keywords?: string[];
  ogImage?: string;
  siteName?: string;
}

/**
 * Applied design system (from AWD-05)
 */
export interface AppliedDesignSystem {
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    text: string;
  };
  typography: {
    headingFont: string;
    bodyFont: string;
    scale: string;
  };
  spacing: {
    scale: string;
  };
  borders: {
    radius: string;
  };
  shadows: {
    style: string;
  };
}

/**
 * Content summary for the generated site
 */
export interface ContentSummary {
  totalPages: number;
  totalComponents: number;
  componentsUsed: string[];
  dataSourcesUsed: string[];
  contentGenerated: {
    headlines: number;
    paragraphs: number;
    buttons: number;
    images: number;
  };
}

/**
 * Main output from website designer
 */
export interface WebsiteDesignerOutput {
  success: boolean;
  error?: string;
  site: {
    name: string;
    domain?: string;
    settings: SiteSettings;
    seo: SEOSettings;
  };
  pages: GeneratedPage[];
  navigation: NavigationStructure;
  designSystem: AppliedDesignSystem;
  contentSummary: ContentSummary;
  estimatedBuildTime: number;
  architecture: SiteArchitecture;
}

// =============================================================================
// ENGINE STATE TYPES
// =============================================================================

/**
 * Generation progress tracking
 */
export interface GenerationProgress {
  stage:
    | "initializing"
    | "building-context"
    | "analyzing-prompt"
    | "creating-architecture"
    | "generating-pages"
    | "generating-shared-elements"
    | "finalizing";
  currentPage?: string;
  pagesComplete: number;
  pagesTotal: number;
  message: string;
}

/**
 * Generation event for streaming
 */
export interface GenerationEvent {
  type: "progress" | "page-complete" | "error" | "complete";
  progress?: GenerationProgress;
  page?: GeneratedPage;
  error?: string;
  result?: WebsiteDesignerOutput;
}

// =============================================================================
// CONTEXT TYPES (RE-EXPORTS)
// =============================================================================

export type { BusinessDataContext } from "./data-context/types";
