/**
 * Premium Blog Templates
 * PHASE-ED-07B: Template System - Premium Templates
 * 
 * 6 premium blog templates with full Puck component structures.
 */

import type { PuckTemplate } from "@/types/puck-templates";

function generateId(): string {
  return `component-${Math.random().toString(36).substring(2, 11)}`;
}

// ============================================
// 1. MAGAZINE / NEWS BLOG
// ============================================

export const magazineBlog: PuckTemplate = {
  id: "premium-magazine",
  name: "Magazine / News",
  slug: "magazine-blog",
  description: "Professional magazine-style blog with featured articles and categories",
  category: "blog",
  subcategory: "magazine",
  tags: ["magazine", "news", "editorial", "articles", "publication"],
  thumbnail: "/templates/premium/magazine.jpg",
  isPremium: true,
  isNew: true,
  isFeatured: true,
  isPopular: true,
  popularity: 94,
  features: [
    "Featured article hero",
    "Category navigation",
    "Trending articles",
    "Newsletter signup",
    "Author profiles",
    "Related posts",
  ],
  sections: ["navbar", "hero", "trending", "categories", "latest", "newsletter", "footer"],
  componentsUsed: ["Navbar", "Hero", "PostGrid", "CategoryNav", "Sidebar", "Newsletter", "Footer"],
  colorScheme: {
    primary: "#dc2626",
    secondary: "#fef2f2",
    accent: "#ef4444",
    background: "#ffffff",
  },
  puckData: {
    root: { props: { title: "Magazine Blog" } },
    content: [
      {
        type: "Navbar",
        props: {
          id: generateId(),
          logo: "THE DAILY",
          links: [
            { label: "News", href: "#news" },
            { label: "Business", href: "#business" },
            { label: "Tech", href: "#tech" },
            { label: "Culture", href: "#culture" },
            { label: "Opinion", href: "#opinion" },
          ],
          showSearch: true,
          ctaText: "Subscribe",
          ctaLink: "#subscribe",
          sticky: true,
          backgroundColor: "#ffffff",
          textColor: "#0f172a",
        },
      },
      {
        type: "FeaturedPost",
        props: {
          id: generateId(),
          title: "The Future of Artificial Intelligence: What 2026 Holds",
          excerpt: "Leading researchers share their predictions on how AI will transform industries, reshape the workforce, and change our daily lives in the coming years.",
          image: "/posts/featured.jpg",
          author: "Sarah Mitchell",
          authorAvatar: "/authors/sarah.jpg",
          date: "January 31, 2026",
          category: "Technology",
          readTime: "8 min read",
          link: "#",
          style: "hero",
          backgroundColor: "#0f172a",
          textColor: "#ffffff",
          padding: "xl",
        },
      },
      {
        type: "CategoryNav",
        props: {
          id: generateId(),
          categories: ["All", "News", "Business", "Technology", "Culture", "Opinion", "Lifestyle"],
          style: "pills",
          alignment: "center",
          backgroundColor: "#f8fafc",
          activeColor: "#dc2626",
          padding: "sm",
        },
      },
      {
        type: "Section",
        props: {
          id: generateId(),
          backgroundColor: "#ffffff",
          padding: "lg",
          columns: "sidebar-right",
        },
      },
      {
        type: "PostGrid",
        props: {
          id: generateId(),
          title: "Trending Now",
          posts: [
            {
              title: "Global Markets React to Policy Changes",
              excerpt: "Financial experts analyze the latest market movements...",
              image: "/posts/markets.jpg",
              author: "James Chen",
              date: "Jan 30, 2026",
              category: "Business",
              link: "#",
            },
            {
              title: "The Rise of Sustainable Fashion",
              excerpt: "How eco-conscious brands are reshaping the industry...",
              image: "/posts/fashion.jpg",
              author: "Emma Rodriguez",
              date: "Jan 29, 2026",
              category: "Culture",
              link: "#",
            },
            {
              title: "New Study Reveals Health Benefits of...",
              excerpt: "Research suggests surprising connections between...",
              image: "/posts/health.jpg",
              author: "Dr. Michael Park",
              date: "Jan 28, 2026",
              category: "Health",
              link: "#",
            },
          ],
          columns: 3,
          showExcerpt: true,
          showAuthor: true,
          showDate: true,
          showCategory: true,
          backgroundColor: "#ffffff",
        },
      },
      {
        type: "Sidebar",
        props: {
          id: generateId(),
          widgets: [
            {
              type: "newsletter",
              title: "Stay Informed",
              description: "Get daily updates delivered to your inbox",
            },
            {
              type: "popular",
              title: "Most Read",
              posts: [
                { title: "10 Tech Trends to Watch", link: "#" },
                { title: "The Best Books of 2025", link: "#" },
                { title: "Interview: CEO on Innovation", link: "#" },
              ],
            },
            {
              type: "tags",
              title: "Popular Topics",
              tags: ["AI", "Climate", "Economy", "Politics", "Tech"],
            },
          ],
        },
      },
      {
        type: "PostGrid",
        props: {
          id: generateId(),
          title: "Latest Articles",
          posts: [
            { title: "Article 1", excerpt: "Description...", image: "/posts/p1.jpg", category: "News", date: "Jan 27", link: "#" },
            { title: "Article 2", excerpt: "Description...", image: "/posts/p2.jpg", category: "Tech", date: "Jan 26", link: "#" },
            { title: "Article 3", excerpt: "Description...", image: "/posts/p3.jpg", category: "Culture", date: "Jan 25", link: "#" },
            { title: "Article 4", excerpt: "Description...", image: "/posts/p4.jpg", category: "Business", date: "Jan 24", link: "#" },
            { title: "Article 5", excerpt: "Description...", image: "/posts/p5.jpg", category: "Opinion", date: "Jan 23", link: "#" },
            { title: "Article 6", excerpt: "Description...", image: "/posts/p6.jpg", category: "Lifestyle", date: "Jan 22", link: "#" },
          ],
          columns: 3,
          pagination: true,
          backgroundColor: "#f8fafc",
          padding: "lg",
        },
      },
      {
        type: "Newsletter",
        props: {
          id: generateId(),
          title: "Subscribe to Our Newsletter",
          subtitle: "Get the latest stories and breaking news delivered to your inbox",
          placeholder: "Enter your email",
          buttonText: "Subscribe",
          backgroundColor: "#dc2626",
          textColor: "#ffffff",
          padding: "lg",
        },
      },
      {
        type: "Footer",
        props: {
          id: generateId(),
          companyName: "THE DAILY",
          description: "Award-winning journalism since 2010",
          columns: [
            {
              title: "Sections",
              links: [
                { label: "News", href: "#" },
                { label: "Business", href: "#" },
                { label: "Tech", href: "#" },
                { label: "Culture", href: "#" },
              ],
            },
            {
              title: "Company",
              links: [
                { label: "About", href: "#" },
                { label: "Careers", href: "#" },
                { label: "Advertise", href: "#" },
                { label: "Contact", href: "#" },
              ],
            },
          ],
          showSocial: true,
          socialLinks: { twitter: "#", facebook: "#", instagram: "#" },
          copyrightText: "© 2026 THE DAILY. All rights reserved.",
          backgroundColor: "#0f172a",
          textColor: "#ffffff",
        },
      },
    ],
    zones: {},
  },
  metadata: {
    author: "DRAMAC",
    version: "1.0.0",
    createdAt: "2026-01-31",
    lastUpdated: "2026-01-31",
    estimatedBuildTime: "30 minutes",
    difficulty: "intermediate",
    componentCount: 10,
    responsive: true,
    darkModeReady: true,
  },
};

// ============================================
// 2. PERSONAL / LIFESTYLE BLOG
// ============================================

export const personalBlog: PuckTemplate = {
  id: "premium-personal-blog",
  name: "Personal / Lifestyle",
  slug: "personal-blog",
  description: "Elegant personal blog for sharing life stories and experiences",
  category: "blog",
  subcategory: "personal",
  tags: ["personal", "lifestyle", "diary", "stories", "journal"],
  thumbnail: "/templates/premium/personal-blog.jpg",
  isPremium: true,
  isNew: false,
  isFeatured: true,
  isPopular: true,
  popularity: 91,
  features: [
    "About hero section",
    "Featured posts",
    "Category filter",
    "Instagram integration",
    "Newsletter",
  ],
  sections: ["navbar", "hero", "about", "featured", "posts", "instagram", "newsletter", "footer"],
  componentsUsed: ["Navbar", "Hero", "About", "PostGrid", "InstagramFeed", "Newsletter", "Footer"],
  colorScheme: {
    primary: "#be185d",
    secondary: "#fdf2f8",
    accent: "#ec4899",
    background: "#ffffff",
  },
  puckData: {
    root: { props: { title: "Personal Blog" } },
    content: [
      {
        type: "Navbar",
        props: {
          id: generateId(),
          logo: "Emma's Journal",
          links: [
            { label: "Home", href: "#" },
            { label: "About", href: "#about" },
            { label: "Travel", href: "#travel" },
            { label: "Lifestyle", href: "#lifestyle" },
            { label: "Food", href: "#food" },
            { label: "Contact", href: "#contact" },
          ],
          showSocial: true,
          socialLinks: { instagram: "#", pinterest: "#" },
          sticky: true,
          backgroundColor: "#ffffff",
        },
      },
      {
        type: "Hero",
        props: {
          id: generateId(),
          title: "Welcome to My Little Corner of the Internet",
          subtitle: "A lifestyle blog about travel, food, fashion, and finding joy in everyday moments",
          alignment: "center",
          buttonText: "Start Reading",
          buttonLink: "#posts",
          backgroundType: "image",
          backgroundImage: "/images/personal-hero.jpg",
          overlay: true,
          overlayOpacity: 0.4,
          textColor: "#ffffff",
          padding: "xl",
        },
      },
      {
        type: "About",
        props: {
          id: generateId(),
          title: "Hey, I'm Emma! 👋",
          content: "I'm a 30-something creative soul living in San Francisco. This blog is my space to share my adventures, favorite recipes, style inspiration, and thoughts on living a meaningful life. When I'm not writing, you'll find me hiking with my dog Luna, trying new restaurants, or planning my next trip.",
          image: "/images/emma-about.jpg",
          imagePosition: "left",
          backgroundColor: "#ffffff",
          padding: "lg",
        },
      },
      {
        type: "PostGrid",
        props: {
          id: generateId(),
          title: "Featured Posts",
          posts: [
            {
              title: "A Week in the South of France",
              excerpt: "My dreamy adventure through lavender fields and charming villages...",
              image: "/posts/france.jpg",
              category: "Travel",
              date: "Jan 20, 2026",
              link: "#",
            },
            {
              title: "My Cozy Morning Routine",
              excerpt: "How I start each day with intention and gratitude...",
              image: "/posts/morning.jpg",
              category: "Lifestyle",
              date: "Jan 15, 2026",
              link: "#",
            },
            {
              title: "The Perfect Homemade Pasta",
              excerpt: "A recipe I learned from an Italian grandmother...",
              image: "/posts/pasta.jpg",
              category: "Food",
              date: "Jan 10, 2026",
              link: "#",
            },
          ],
          columns: 3,
          style: "card",
          showCategory: true,
          showDate: true,
          backgroundColor: "#fdf2f8",
          padding: "lg",
        },
      },
      {
        type: "CategoryNav",
        props: {
          id: generateId(),
          categories: ["All Posts", "Travel", "Lifestyle", "Food", "Fashion", "Wellness"],
          style: "minimal",
          alignment: "center",
          backgroundColor: "#ffffff",
          padding: "sm",
        },
      },
      {
        type: "PostGrid",
        props: {
          id: generateId(),
          title: "Recent Posts",
          posts: [
            { title: "Post 1", image: "/posts/r1.jpg", category: "Travel", date: "Jan 28", link: "#" },
            { title: "Post 2", image: "/posts/r2.jpg", category: "Food", date: "Jan 25", link: "#" },
            { title: "Post 3", image: "/posts/r3.jpg", category: "Lifestyle", date: "Jan 22", link: "#" },
            { title: "Post 4", image: "/posts/r4.jpg", category: "Fashion", date: "Jan 19", link: "#" },
            { title: "Post 5", image: "/posts/r5.jpg", category: "Wellness", date: "Jan 16", link: "#" },
            { title: "Post 6", image: "/posts/r6.jpg", category: "Travel", date: "Jan 13", link: "#" },
          ],
          columns: 3,
          pagination: true,
          backgroundColor: "#ffffff",
          padding: "lg",
        },
      },
      {
        type: "InstagramFeed",
        props: {
          id: generateId(),
          title: "Follow Along @emmasjournal",
          username: "emmasjournal",
          postCount: 6,
          columns: 6,
          showFollowButton: true,
          backgroundColor: "#fdf2f8",
          padding: "md",
        },
      },
      {
        type: "Newsletter",
        props: {
          id: generateId(),
          title: "Join the Community",
          subtitle: "Subscribe for weekly inspiration, exclusive content, and a free travel guide!",
          placeholder: "Your email address",
          buttonText: "Subscribe",
          backgroundColor: "#be185d",
          textColor: "#ffffff",
          padding: "lg",
        },
      },
      {
        type: "Footer",
        props: {
          id: generateId(),
          companyName: "Emma's Journal",
          description: "Living life one adventure at a time ✨",
          showSocial: true,
          socialLinks: { instagram: "#", pinterest: "#", youtube: "#" },
          copyrightText: "© 2026 Emma's Journal. Made with ❤️ in San Francisco",
          backgroundColor: "#ffffff",
          textColor: "#6b7280",
        },
      },
    ],
    zones: {},
  },
  metadata: {
    author: "DRAMAC",
    version: "1.0.0",
    createdAt: "2026-01-31",
    lastUpdated: "2026-01-31",
    estimatedBuildTime: "25 minutes",
    difficulty: "beginner",
    componentCount: 9,
    responsive: true,
    darkModeReady: true,
  },
};

// ============================================
// 3. TECH / TUTORIAL BLOG
// ============================================

export const techBlog: PuckTemplate = {
  id: "premium-tech-blog",
  name: "Tech / Tutorial",
  slug: "tech-blog",
  description: "Developer-focused tech blog with code snippets and tutorials",
  category: "blog",
  subcategory: "tech",
  tags: ["tech", "coding", "tutorials", "development", "programming"],
  thumbnail: "/templates/premium/tech-blog.jpg",
  isPremium: true,
  isNew: true,
  isFeatured: false,
  isPopular: true,
  popularity: 89,
  features: [
    "Code-friendly design",
    "Category filtering",
    "Series/collections",
    "Newsletter",
    "Search functionality",
  ],
  sections: ["navbar", "hero", "featured", "categories", "posts", "newsletter", "footer"],
  componentsUsed: ["Navbar", "Hero", "PostGrid", "CategoryNav", "Newsletter", "Footer"],
  colorScheme: {
    primary: "#6366f1",
    secondary: "#eef2ff",
    accent: "#818cf8",
    background: "#0f172a",
  },
  puckData: {
    root: { props: { title: "Tech Blog" } },
    content: [
      {
        type: "Navbar",
        props: {
          id: generateId(),
          logo: "{ DevBlog }",
          links: [
            { label: "Tutorials", href: "#tutorials" },
            { label: "Articles", href: "#articles" },
            { label: "Guides", href: "#guides" },
            { label: "Resources", href: "#resources" },
            { label: "About", href: "#about" },
          ],
          showSearch: true,
          ctaText: "RSS",
          ctaLink: "#rss",
          sticky: true,
          backgroundColor: "#0f172a",
          textColor: "#ffffff",
        },
      },
      {
        type: "Hero",
        props: {
          id: generateId(),
          title: "Learn. Build. Ship.",
          subtitle: "Practical tutorials and articles on web development, DevOps, and modern software engineering.",
          alignment: "center",
          buttonText: "Browse Tutorials",
          buttonLink: "#tutorials",
          backgroundType: "gradient",
          gradientFrom: "#6366f1",
          gradientTo: "#8b5cf6",
          textColor: "#ffffff",
          padding: "lg",
        },
      },
      {
        type: "PostGrid",
        props: {
          id: generateId(),
          title: "Featured Tutorials",
          posts: [
            {
              title: "Building a Full-Stack App with Next.js 16",
              excerpt: "Complete guide to building modern applications with the latest Next.js features...",
              image: "/posts/nextjs.jpg",
              category: "Next.js",
              readTime: "25 min",
              difficulty: "Intermediate",
              link: "#",
            },
            {
              title: "Mastering TypeScript Generics",
              excerpt: "Deep dive into TypeScript's powerful generic types...",
              image: "/posts/typescript.jpg",
              category: "TypeScript",
              readTime: "15 min",
              difficulty: "Advanced",
              link: "#",
            },
            {
              title: "Docker for Beginners: A Complete Guide",
              excerpt: "Everything you need to know to get started with Docker...",
              image: "/posts/docker.jpg",
              category: "DevOps",
              readTime: "20 min",
              difficulty: "Beginner",
              link: "#",
            },
          ],
          columns: 3,
          showReadTime: true,
          showDifficulty: true,
          backgroundColor: "#1e293b",
          textColor: "#ffffff",
          padding: "lg",
        },
      },
      {
        type: "CategoryNav",
        props: {
          id: generateId(),
          categories: ["All", "React", "Next.js", "TypeScript", "Node.js", "DevOps", "AWS", "CSS"],
          style: "tags",
          alignment: "center",
          backgroundColor: "#0f172a",
          textColor: "#94a3b8",
          activeColor: "#6366f1",
          padding: "md",
        },
      },
      {
        type: "PostGrid",
        props: {
          id: generateId(),
          title: "Latest Articles",
          posts: [
            { title: "React Server Components Explained", category: "React", readTime: "10 min", link: "#" },
            { title: "10 VS Code Extensions for Productivity", category: "Tools", readTime: "8 min", link: "#" },
            { title: "CI/CD with GitHub Actions", category: "DevOps", readTime: "15 min", link: "#" },
            { title: "CSS Grid Layout Masterclass", category: "CSS", readTime: "12 min", link: "#" },
            { title: "Authentication Best Practices", category: "Security", readTime: "18 min", link: "#" },
            { title: "PostgreSQL Performance Tips", category: "Database", readTime: "14 min", link: "#" },
          ],
          columns: 2,
          style: "list",
          showReadTime: true,
          pagination: true,
          backgroundColor: "#1e293b",
          textColor: "#ffffff",
          padding: "lg",
        },
      },
      {
        type: "Newsletter",
        props: {
          id: generateId(),
          title: "Level Up Your Skills",
          subtitle: "Weekly tutorials, tips, and resources delivered to your inbox. No spam, ever.",
          placeholder: "your@email.com",
          buttonText: "Subscribe",
          backgroundColor: "#6366f1",
          textColor: "#ffffff",
          padding: "lg",
        },
      },
      {
        type: "Footer",
        props: {
          id: generateId(),
          companyName: "{ DevBlog }",
          description: "Practical tutorials for modern developers",
          columns: [
            {
              title: "Topics",
              links: [
                { label: "React", href: "#" },
                { label: "Next.js", href: "#" },
                { label: "TypeScript", href: "#" },
                { label: "DevOps", href: "#" },
              ],
            },
            {
              title: "Resources",
              links: [
                { label: "Cheat Sheets", href: "#" },
                { label: "Code Snippets", href: "#" },
                { label: "Tools", href: "#" },
                { label: "Books", href: "#" },
              ],
            },
          ],
          showSocial: true,
          socialLinks: { twitter: "#", github: "#", youtube: "#" },
          copyrightText: "© 2026 DevBlog. Built with Next.js",
          backgroundColor: "#0f172a",
          textColor: "#94a3b8",
        },
      },
    ],
    zones: {},
  },
  metadata: {
    author: "DRAMAC",
    version: "1.0.0",
    createdAt: "2026-01-31",
    lastUpdated: "2026-01-31",
    estimatedBuildTime: "25 minutes",
    difficulty: "intermediate",
    componentCount: 7,
    responsive: true,
    darkModeReady: true,
  },
};

// ============================================
// 4. FOOD / RECIPE BLOG
// ============================================

export const foodBlog: PuckTemplate = {
  id: "premium-food-blog",
  name: "Food / Recipe",
  slug: "food-blog",
  description: "Beautiful food blog with recipe cards and cooking guides",
  category: "blog",
  subcategory: "food",
  tags: ["food", "recipes", "cooking", "culinary", "kitchen"],
  thumbnail: "/templates/premium/food-blog.jpg",
  isPremium: true,
  isNew: false,
  isFeatured: true,
  isPopular: true,
  popularity: 92,
  features: [
    "Recipe cards",
    "Course filtering",
    "Print-friendly",
    "Video integration",
    "Newsletter",
  ],
  sections: ["navbar", "hero", "featured", "categories", "recipes", "about", "newsletter", "footer"],
  componentsUsed: ["Navbar", "Hero", "RecipeGrid", "CategoryNav", "About", "Newsletter", "Footer"],
  colorScheme: {
    primary: "#ea580c",
    secondary: "#fff7ed",
    accent: "#f97316",
    background: "#ffffff",
  },
  puckData: {
    root: { props: { title: "Food Blog" } },
    content: [
      {
        type: "Navbar",
        props: {
          id: generateId(),
          logo: "🍳 Savory Bites",
          links: [
            { label: "Recipes", href: "#recipes" },
            { label: "Meal Prep", href: "#mealprep" },
            { label: "Quick & Easy", href: "#quick" },
            { label: "Baking", href: "#baking" },
            { label: "About", href: "#about" },
          ],
          showSearch: true,
          sticky: true,
          backgroundColor: "#ffffff",
        },
      },
      {
        type: "Hero",
        props: {
          id: generateId(),
          title: "Simple Recipes, Amazing Flavors",
          subtitle: "Delicious, tested recipes that anyone can make. From quick weeknight dinners to impressive weekend projects.",
          alignment: "center",
          buttonText: "Browse Recipes",
          buttonLink: "#recipes",
          backgroundType: "image",
          backgroundImage: "/images/food-hero.jpg",
          overlay: true,
          overlayOpacity: 0.5,
          textColor: "#ffffff",
          padding: "xl",
        },
      },
      {
        type: "RecipeGrid",
        props: {
          id: generateId(),
          title: "Popular This Week",
          recipes: [
            {
              title: "Creamy Tuscan Chicken",
              image: "/recipes/tuscan-chicken.jpg",
              prepTime: "15 min",
              cookTime: "30 min",
              servings: 4,
              difficulty: "Easy",
              category: "Dinner",
              link: "#",
            },
            {
              title: "Classic Banana Bread",
              image: "/recipes/banana-bread.jpg",
              prepTime: "10 min",
              cookTime: "55 min",
              servings: 8,
              difficulty: "Easy",
              category: "Baking",
              link: "#",
            },
            {
              title: "Thai Basil Stir-Fry",
              image: "/recipes/thai-stir-fry.jpg",
              prepTime: "10 min",
              cookTime: "10 min",
              servings: 4,
              difficulty: "Easy",
              category: "Quick",
              link: "#",
            },
          ],
          columns: 3,
          showTime: true,
          showServings: true,
          showDifficulty: true,
          backgroundColor: "#fff7ed",
          padding: "lg",
        },
      },
      {
        type: "CategoryNav",
        props: {
          id: generateId(),
          categories: ["All Recipes", "Breakfast", "Lunch", "Dinner", "Desserts", "Vegetarian", "Quick & Easy"],
          style: "pills",
          alignment: "center",
          backgroundColor: "#ffffff",
          activeColor: "#ea580c",
          padding: "md",
        },
      },
      {
        type: "RecipeGrid",
        props: {
          id: generateId(),
          title: "Latest Recipes",
          recipes: [
            { title: "Recipe 1", image: "/recipes/r1.jpg", prepTime: "20 min", category: "Dinner", link: "#" },
            { title: "Recipe 2", image: "/recipes/r2.jpg", prepTime: "15 min", category: "Lunch", link: "#" },
            { title: "Recipe 3", image: "/recipes/r3.jpg", prepTime: "45 min", category: "Baking", link: "#" },
            { title: "Recipe 4", image: "/recipes/r4.jpg", prepTime: "10 min", category: "Breakfast", link: "#" },
            { title: "Recipe 5", image: "/recipes/r5.jpg", prepTime: "30 min", category: "Dinner", link: "#" },
            { title: "Recipe 6", image: "/recipes/r6.jpg", prepTime: "25 min", category: "Vegetarian", link: "#" },
          ],
          columns: 3,
          pagination: true,
          backgroundColor: "#ffffff",
          padding: "lg",
        },
      },
      {
        type: "About",
        props: {
          id: generateId(),
          title: "Hi, I'm Chef Maria! 👩‍🍳",
          content: "Welcome to Savory Bites! I'm a home cook passionate about creating delicious, approachable recipes. After 15 years of recipe development and testing, I've learned that the best food doesn't need to be complicated. Here you'll find tested recipes that actually work, with tips and techniques to help you become a better cook.",
          image: "/images/maria.jpg",
          imagePosition: "left",
          backgroundColor: "#fff7ed",
          padding: "lg",
        },
      },
      {
        type: "Newsletter",
        props: {
          id: generateId(),
          title: "Get New Recipes Weekly",
          subtitle: "Join 50,000+ home cooks and get free recipes, tips, and cooking inspiration",
          placeholder: "Enter your email",
          buttonText: "Subscribe",
          incentive: "Plus get my FREE 'Quick Dinners' ebook!",
          backgroundColor: "#ea580c",
          textColor: "#ffffff",
          padding: "lg",
        },
      },
      {
        type: "Footer",
        props: {
          id: generateId(),
          companyName: "Savory Bites",
          description: "Delicious recipes for home cooks",
          columns: [
            {
              title: "Recipes",
              links: [
                { label: "Dinner", href: "#" },
                { label: "Quick & Easy", href: "#" },
                { label: "Baking", href: "#" },
                { label: "Vegetarian", href: "#" },
              ],
            },
            {
              title: "Resources",
              links: [
                { label: "Meal Plans", href: "#" },
                { label: "Cooking Tips", href: "#" },
                { label: "Kitchen Tools", href: "#" },
                { label: "FAQ", href: "#" },
              ],
            },
          ],
          showSocial: true,
          socialLinks: { instagram: "#", pinterest: "#", youtube: "#", facebook: "#" },
          copyrightText: "© 2026 Savory Bites. All rights reserved.",
          backgroundColor: "#1f2937",
          textColor: "#ffffff",
        },
      },
    ],
    zones: {},
  },
  metadata: {
    author: "DRAMAC",
    version: "1.0.0",
    createdAt: "2026-01-31",
    lastUpdated: "2026-01-31",
    estimatedBuildTime: "25 minutes",
    difficulty: "beginner",
    componentCount: 8,
    responsive: true,
    darkModeReady: true,
  },
};

// ============================================
// ALL BLOG TEMPLATES
// ============================================

export const BLOG_TEMPLATES: PuckTemplate[] = [
  magazineBlog,
  personalBlog,
  techBlog,
  foodBlog,
];

export default BLOG_TEMPLATES;
